#!/usr/bin/env python3
"""
en_content.py - the EN client's own content, loaded once (roadmap 1.8 F7: arch-content-loader)
==============================================================================================
The EN 2008 client is the authority for ids, names, topology and every rule it computes
itself; `gamedef.sqlite3` (KR) only supplies numbers the EN files do not carry, and never
an id (F7 table, item_inventory.md 3.1, quest_cards_misc.md 3.1).

    import en_content as EC
    EC.items().get(179).kind          # 11  (hs/windslayer.hii, def+0x1CC)
    EC.items().exists(4356)           # False -> the client would ignore the grant (S2-11)
    EC.items().tab_of(5)              # 'consume'
    EC.quests().get(26).send          # [(179, 1)]  decimal, not hex (Q-B1)
    EC.cards().get(2030).card_npc     # 1   (Pupu card)
    EC.item_name(179)                 # 'Wooden Stick' (EN, from the client's own table)
    EC.portal(101, 23)                # (102, x, y)
    EC.npcs().get(1).name             # 'Pupu' (hs/windslayer.hni + hs/NPCLngKo.lng)
    EC.npcs().template_index(1)       # 1   (the S2C 0x1A template_index)
    EC.map_spawns(102)                # 8 x Spawn(npc=1, ...) from the map's event-2 tiles
    EC.gamedef_npc(1)                 # KR monster row (only for columns the hni lacks)
    EC.reload()                       # GM /update: drop every cache

Sources (F7)
------------
| data                              | file                                    |
|-----------------------------------|-----------------------------------------|
| items / skills / cards            | `<client>/hs/windslayer.hii`  (4248)    |
| quests                            | `<client>/hs/windslayer.hqi`  (291)     |
| NPC / monster templates (0x1A)    | `<client>/hs/windslayer.hni`  (180) + `hs/NPCLngKo.lng` names |
| EN item names                     | `server/en_item_catalog.json` (live dump)|
| KR-only columns                   | `server/gamedef.sqlite3`                |
| portals / arrival points          | `server/portals_en.json`, generated by en_maps.py from the EN .hmi/.hsi |
| monster spawn points              | the EN .hmi event-2 tiles (en_maps.py)  |

Asset cipher (reference_asset_formats, quest_cards_misc E1): `plain[i] = (raw[i] +
[0xE9,0xDE,0xE0][i % 3]) & 0xFF` over the file minus its 20-byte SHA-1 footer. The plain
text is `Number_of_X: N` followed by one CRLF line per record: leading positional tokens
(id, and the title text id in the hqi), then `Key: value...` pairs whose value can be
several tokens (`Job: 1 0 0 0 0 0 0`).

Numbers are DECIMAL everywhere. The old `quest_defs.py` read the hqi id/count arrays as
hex and only 10 reward entries, which decodes 242 of the 291 quests wrongly (Q-B1): quest
26 "sends" 377 instead of the Wooden Stick 179 and loses the Double Jump reward, which is
what `_EN_ITEM_OVERRIDE = {377: 179}` was papering over. Both are retired by this module.

EN 2009 build (client-2009-world): configure(CLIENT_DIR_2009, '2009') reads the 2009 install
(WindSlayer2009/hs: 4322 items, the 205-line hni = 204 templates, 266 stage maps + 18
instance-dungeon stages + 4 scene files = 288 .hmi). Per build: the portal table
(portals_en_2009.json, `python en_maps.py --build 2009`), item names (the 2009 client's own
plaintext hs/ITMLngKo.lng by hii Title id; en_item_catalog.json is a 2008 dump) and the item
Kind -> equip slot switch (inventory.kind_tables via ItemCatalog.client_build).

Missing client files: every catalog degrades instead of raising, so a server copied without
`hs/` still starts. ItemCatalog then falls back to `en_item_catalog.json` (ids + Type + EN
names, dumped from the running client), which is enough for the id gate; QuestCatalog and
CardCatalog come up empty and every quest/card path refuses. Each fallback logs once.
"""
import json
import logging
import os
import pathlib
import re
import sqlite3
import threading

log = logging.getLogger('WS')

HERE = os.path.dirname(os.path.abspath(__file__))
# The client install (…/WindSlayer2Game) holds `hs/`; the server lives inside it.
DEFAULT_CLIENT_DIR = os.path.dirname(HERE)
ITEM_CATALOG_JSON = os.path.join(HERE, 'en_item_catalog.json')
GAMEDEF_PATH = os.path.join(HERE, 'gamedef.sqlite3')
# The KR-derived table: only a fallback now (world-portal-table-en), used when neither the
# generated EN table nor the client map files are available.
PORTALS_PATH = os.path.join(HERE, 'portals.json')
PORTALS_EN_PATH = os.path.join(HERE, 'portals_en.json')
# client-2009-world: one generated table per client build. The 2009 map files move 285 of
# the 579 portal lines (only 294 rows equal the 2008 table), so a 2009 server must never
# read the 2008 file.
PORTALS_EN_PATHS = {'2008': PORTALS_EN_PATH, '2009': os.path.join(HERE, 'portals_en_2009.json')}

# Asset cipher (hs/*.hii, *.hqi, *.hni, *.hmi): additive per byte, 3-byte cycle, and a
# 20-byte SHA-1 footer appended by the packer (ValidationCheck.dll).
HS_ADD = (0xE9, 0xDE, 0xE0)
HS_FOOTER_BYTES = 20
# The client's item table (hii header "Number_of_ITEM: 4248"). FUN_00404210 returns NULL
# for id 0 or an id past the table and every item handler then silently does nothing, so
# an id outside 1..EN_ITEM_MAX_ID must never reach the wire or the bag model (S2-11).
EN_ITEM_MAX_ID = 4248
# hii `Type` (def+0x154) -> the bag tab the client files the item in (item_inventory 1.2).
# Types 3 (skill book) and 4 (class change) are consumed on receipt and have no tab.
TAB_BY_TYPE = {0: 'consume', 1: 'equip', 2: 'etc', 5: 'cash'}
TYPE_CONSUMABLE, TYPE_EQUIPMENT, TYPE_ETC, TYPE_SKILL, TYPE_CLASS_CHANGE, TYPE_CASH = 0, 1, 2, 3, 4, 5
# Card deck (quest_cards_misc 1.4): the 64 registrable Monster Cards (Type 2 + CardSpr). The
# deck label's total is NOT this: it is [itemtable+0x24] = the items with CardNpc != 0, 880 in
# 2008 and 900 in 2009 (live quest_cards_misc#13, spec correction C22).
TOTAL_CARDS = 64
# Client-side array widths of one hqi quest line (FUN_00409FE0: %04d ids, %03d counts).
QUEST_SEND_SLOTS = QUEST_DEMAND_SLOTS = 10
QUEST_REWARD_SLOTS = 20
QUEST_JOB_FLAGS = 21          # job[class + JOB_CLASSES * tier]
JOB_CLASSES = 7               # 7 classes x 3 tiers = the 21 flag chars


class ContentError(RuntimeError):
    pass


# ------------------------------------------------------------- asset cipher ---
def decode_hs(path):
    """Plain bytes of one `hs/` asset file: undo the additive cipher and drop the SHA-1
    footer. Raises OSError when the file is missing (callers decide the fallback)."""
    with open(path, 'rb') as f:
        raw = f.read()
    if len(raw) <= HS_FOOTER_BYTES:
        raise ContentError(f'{path}: {len(raw)} B is not a packed hs file')
    body = raw[:-HS_FOOTER_BYTES]
    return bytes((b + HS_ADD[i % 3]) & 0xFF for i, b in enumerate(body))


def decode_hs_text(path):
    """`decode_hs` as text. The tables hold ASCII numbers plus cp949 strings (the client's
    codepage), so a stray byte never aborts the load."""
    return decode_hs(path).decode('cp949', 'replace')


def _split_record(line, positional):
    """(leading tokens, {key: [value tokens]}) for one `<id> [<title>] Key: v ...` line."""
    tokens = line.split()
    fields, key = {}, None
    for token in tokens[positional:]:
        if len(token) > 1 and token.endswith(':'):
            key = token[:-1]
            fields[key] = []
        elif key is not None:
            fields[key].append(token)
    return tokens[:positional], fields


def _int(tokens, default=0):
    """First token of a field as an int (the hs files write plain decimal)."""
    if not tokens:
        return default
    try:
        return int(tokens[0], 10)
    except ValueError:
        return default


def _ints(tokens):
    out = []
    for t in tokens:
        try:
            out.append(int(t, 10))
        except ValueError:
            out.append(0)
    return out


def _digit_groups(tokens, count, width):
    """`count` fixed-width decimal fields of one packed string ("0179000..." -> [179, 0, ...]).
    A short or missing string pads with zeros instead of raising: the loader must not lose
    291 quests over one malformed line."""
    text = tokens[0] if tokens else ''
    out = []
    for i in range(count):
        chunk = text[i * width:(i + 1) * width]
        try:
            out.append(int(chunk, 10))
        except ValueError:
            out.append(0)
    return out


def _pairs(ids, counts):
    """[(id, count)] for the non-zero id slots, with a missing count read as 1 (the client
    grants at least one; Send_Num 000 with a real id does not occur in the EN tables)."""
    return [(i, counts[n] if n < len(counts) and counts[n] else 1)
            for n, i in enumerate(ids) if i]


# ------------------------------------------------------------------- items ---
class ItemDef:
    """One hii record. Attribute names follow the design doc's column mapping
    (item_inventory.md 1.1), not the client's offsets."""
    __slots__ = ('id', 'title_text', 'type', 'sprite', 'hp', 'mp', 'job', 'job2', 'kind',
                 'spr_num', 'gender', 'con', 'skill_lv', 'text', 'lv', 'buy', 'sell',
                 'pmoney', 'ct', 'card_spr', 'card_npc', 'cash', 'cash_cls', 'cash_t',
                 'cash_p', 'cash_v', 'cash_b', 'cash_st', 'union_ids', 'union_counts', 'union_kind',
                 'w_att', 'defense', 's_att', 'stat_str', 'stat_dex', 'stat_int', 'stat_tol', 'mhp', 'mmp',
                 'attribute', 'attri_atk', 'attri_def', 'skill_p_a', 'skill_p_d',
                 'skill_a_a', 'skill_a_d')

    def __init__(self, item_id, fields):
        f = fields
        self.id = item_id
        self.title_text = _int(f.get('Title'))
        self.type = _int(f.get('Type'))
        self.sprite = _int(f.get('Sprite'))
        self.hp = _int(f.get('HP'))
        self.mp = _int(f.get('MP'))
        self.job = _ints(f.get('Job', []))                  # 7 class flags, job[0] = any
        self.job2 = _ints(f.get('Job2', []))
        self.kind = _int(f.get('Kind'), -1)                 # def+0x1CC, equipment only
        self.spr_num = _int(f.get('Spr_Num'))               # worn body sprite
        self.gender = _int(f.get('Gender'))
        self.con = _int(f.get('Con'))                       # def+0x1C8 buff duration (proven live)
        self.skill_lv = _int(f.get('Skill_Lv'))
        self.text = _int(f.get('Text'))
        self.lv = _int(f.get('Lv'))
        self.buy = _int(f.get('Buy'))
        self.sell = _int(f.get('Sell'))
        self.pmoney = _int(f.get('PMoney'))                 # Victy price
        self.ct = _int(f.get('CT'))                         # cooldown ms
        self.card_spr = _int(f.get('CardSpr'))
        self.card_npc = _int(f.get('CardNpc'))
        self.cash = _int(f.get('Cash'))                     # def+0x1F0: no sell/drop/trade
        self.cash_cls = _int(f.get('Cash_Cls'))
        self.cash_t = _int(f.get('Cash_T'))
        self.cash_p = _int(f.get('Cash_P'))                 # def+0x1FC Item Mall price (Wind Cash)
        # premium_cash-catalog (P8): the rest of the mall columns the hii carries (cash.py).
        self.cash_v = _int(f.get('Cash_V'))                 # count (Cash_T 1) or days (Cash_T 2)
        self.cash_b = _int(f.get('Cash_B'))                 # shop badge 0..5
        self.cash_st = _int(f.get('Cash_ST'))               # 0 / 1 / 2 / 5, meaning unknown
        self.union_ids = _digit_groups(f.get('Union', []), 8, 4)
        self.union_counts = _digit_groups(f.get('Union_Cnt', []), 8, 4)
        self.union_kind = _int(f.get('Union_Kind'))
        self.w_att = _int(f.get('W_Att'))
        self.defense = _int(f.get('Def'))
        self.s_att = _int(f.get('S_Att'))
        self.stat_str = _int(f.get('Str'))
        self.stat_dex = _int(f.get('Dex'))
        self.stat_int = _int(f.get('Int'))
        self.stat_tol = _int(f.get('Tol'))
        self.mhp = _int(f.get('mHP'))                       # def+0x160: max HP while slotted
        self.mmp = _int(f.get('mMP'))                       # def+0x164
        # Skill / option columns (combat_skill.md 1.1, cs-skill-defs). `attribute` is def+0x190:
        # the element of an attack skill, and for an option stone worn in an equipment block
        # the kind of bonus FUN_0041ACE0 applies (1 max-HP, 2 max-MP, 3 HP regen, 4 MP regen).
        self.attribute = _int(f.get('Attribute'))
        self.attri_atk = _int(f.get('Attri_Atk'))           # def+0x1A0
        self.attri_def = _int(f.get('Attri_Def'))           # def+0x1A4
        self.skill_p_a = _int(f.get('Skill_P_A'))           # def+0x1B8..+0x1C4: stat modifiers
        self.skill_p_d = _int(f.get('Skill_P_D'))           # while a buff slot is active
        self.skill_a_a = _int(f.get('Skill_A_A'))
        self.skill_a_d = _int(f.get('Skill_A_D'))

    @property
    def tab(self):
        return TAB_BY_TYPE.get(self.type)

    @property
    def is_cash(self):
        """def+0x1F0 != 0: the client refuses to sell, drop, deposit or trade it."""
        return self.cash != 0

    @property
    def recipe(self):
        """[(material id, count)] of the Union columns (crafting, item_inventory F11)."""
        return _pairs(self.union_ids, self.union_counts)

    @property
    def name(self):
        return item_name(self.id)

    def __repr__(self):
        return f'<ItemDef {self.id} {self.name!r} type={self.type} kind={self.kind}>'


class ItemCatalog:
    """The EN item table. `exists` is the single id gate every grant, drop, shop and quest
    path goes through (S2-11: the client silently ignores an id past its table)."""

    def __init__(self, defs, source, max_id=EN_ITEM_MAX_ID, client_build=None):
        self.defs = defs
        self.source = source
        # The table size of THIS catalog: 4248 in the 2008 hii, 4322 in the 2009 one
        # (client-2009-world). The client's own lookup returns NULL past its table.
        self.max_id = max_id
        # The client build whose files these are (items() sets it). Rules keyed by the
        # item's own columns - the Kind -> equip slot switch (inventory.kind_tables) - follow
        # it, so a record never meets the other build's table.
        self.client_build = client_build

    @classmethod
    def load(cls, path):
        text = decode_hs_text(path)
        defs = {}
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith('Number_of_'):
                continue
            head, fields = _split_record(line, 1)
            try:
                item_id = int(head[0], 10)
            except (IndexError, ValueError):
                continue
            defs[item_id] = ItemDef(item_id, fields)
        if not defs:
            raise ContentError(f'{path}: no item records')
        return cls(defs, path, max(defs))

    @classmethod
    def from_dump(cls, path):
        """Fallback: the live client dump (`en_item_catalog.json`), which carries only the
        id, EN name and Type. Enough for the id gate and the 0x15 Type routing; every
        numeric rule (price, Kind, cooldown) is missing, so callers see kind -1 / buy 0."""
        with open(path, encoding='utf-8') as f:
            raw = json.load(f)
        defs = {int(k): ItemDef(int(k), {'Type': [str(v.get('type', 0))]}) for k, v in raw.items()}
        return cls(defs, path, max(defs) if defs else EN_ITEM_MAX_ID)

    def get(self, item_id):
        try:
            return self.defs.get(int(item_id))
        except (TypeError, ValueError):
            return None

    def exists(self, item_id):
        """True when the EN client has a definition for this id. Anything else (0, a KR-only
        id above 4248, a non-number) never changes server state and never goes on the wire."""
        if isinstance(item_id, bool):          # True is not item 1
            return False
        try:
            item_id = int(item_id)
        except (TypeError, ValueError):
            return False
        if not 1 <= item_id <= self.max_id:
            return False
        return item_id in self.defs

    def type_of(self, item_id):
        """Client item Type (0 stack, 1 equipment, 2 etc, 3 skill book, 4 class change,
        5 cash), or None for an id the EN client does not have."""
        d = self.get(item_id)
        return None if d is None else d.type

    def tab_of(self, item_id):
        """Bag tab name ('consume' / 'equip' / 'etc' / 'cash') or None for a type the client
        consumes on receipt (skill book, class change) or an unknown id."""
        d = self.get(item_id)
        return None if d is None else d.tab

    def kind_of(self, item_id):
        d = self.get(item_id)
        return None if d is None or d.kind < 0 else d.kind

    def price(self, item_id, qty=1, victy=False):
        """u64 cost of `qty` of this item (shop_storage 1.3: compute in u64, never trust the
        client's 32-bit check)."""
        d = self.get(item_id)
        if d is None:
            return 0
        return max(0, int(d.pmoney if victy else d.buy)) * max(0, int(qty))

    def ids_of_type(self, item_type):
        return [i for i, d in self.defs.items() if d.type == item_type]

    def filter_ids(self, ids):
        """The ids of `ids` the EN client actually has (drop tables, shop lists, rewards)."""
        return [i for i in ids if self.exists(i)]

    def __len__(self):
        return len(self.defs)

    def __contains__(self, item_id):
        return self.exists(item_id)


# ------------------------------------------------------------------- cards ---
class CardCatalog:
    """Monster cards: hii Type 2 records with CardSpr != 0 (64 in EN). `card_npc` is the
    monster npccode the card belongs to (quest_cards_misc 3.1)."""

    def __init__(self, defs):
        self.defs = defs

    @classmethod
    def from_items(cls, catalog):
        return cls({i: d for i, d in catalog.defs.items()
                    if d.type == TYPE_ETC and d.card_spr})

    def get(self, item_id):
        try:
            return self.defs.get(int(item_id))
        except (TypeError, ValueError):
            return None

    def exists(self, item_id):
        return self.get(item_id) is not None

    def for_npc(self, npccode):
        """The card ids that belong to this monster npccode (card EXP bonus, Q2)."""
        return [i for i, d in self.defs.items() if d.card_npc == npccode]

    def __len__(self):
        return len(self.defs)


# ------------------------------------------------------------------ quests ---
class QuestDef:
    """One hqi quest line. Everything is decimal (FUN_00409FE0 `%04d` / `%03d`)."""
    __slots__ = ('idx', 'title_text', 'send', 'reward', 'demand', 'job', 'exp', 'money',
                 'start_lev', 'end_lev', 'repeat', 'explain', 'reqpro', 'npc', 'prev_q',
                 'next_q', 'snpc', 'enpc', 'dialogs', 'intro', 'completed_text', 'indun_map')

    def __init__(self, idx, title_text, fields):
        f = fields
        self.idx = idx
        self.title_text = title_text
        self.send = _pairs(_digit_groups(f.get('Send', []), QUEST_SEND_SLOTS, 4),
                           _digit_groups(f.get('Send_Num', []), QUEST_SEND_SLOTS, 3))
        self.reward = _pairs(_digit_groups(f.get('Reward', []), QUEST_REWARD_SLOTS, 4),
                             _digit_groups(f.get('Reward_Num', []), QUEST_REWARD_SLOTS, 3))
        self.demand = _pairs(_digit_groups(f.get('Demand', []), QUEST_DEMAND_SLOTS, 4),
                             _digit_groups(f.get('Demand_Num', []), QUEST_DEMAND_SLOTS, 3))
        self.job = (f.get('Job') or [''])[0]                 # 21 flag chars
        self.exp = _int(f.get('Exp'))
        self.money = _int(f.get('Money'))                    # signed: < 0 is a fee
        self.start_lev = _int(f.get('Start_Lev'))
        self.end_lev = _int(f.get('End_Lev'))
        self.repeat = _int(f.get('Repeat'))
        self.explain = _int(f.get('Explain'))
        self.reqpro = _int(f.get('ReqPro'))                  # kill count
        self.npc = _int(f.get('NPC'))                        # npccode to kill (E5)
        self.prev_q = _int(f.get('PrevQuest'))
        self.next_q = _int(f.get('NextQuest'))
        self.snpc = _int(f.get('SNPC'))                      # offering NPC (0 = never offered)
        self.enpc = _int(f.get('ENPC'))                      # turn-in NPC
        self.intro = _int(f.get('Intro'))
        self.completed_text = _int(f.get('Completed'))
        self.dialogs = (_int(f.get('First')), _int(f.get('Ing')),
                        _int(f.get('Finish')), _int(f.get('None')))
        self.indun_map = (f.get('IndunMapName') or ['None'])[0]

    @property
    def needs_slot(self):
        """False for the 9 talk-only quests: the client files those straight into the
        completed list and uses no active slot (quest_cards_misc 1.3, Q-B3)."""
        return self.money < 0 or bool(self.demand) or self.reqpro != 0

    def job_allows(self, class_id, tier=0):
        """The hqi Job string indexed `class + 7 * tier` (quest_cards_misc E1). An absent or
        short string allows everyone, which is how the client reads a missing flag."""
        index = int(class_id) + JOB_CLASSES * int(tier)
        if not self.job or not 0 <= index < len(self.job):
            return True
        return self.job[index] == '1'

    def __repr__(self):
        return (f'<QuestDef {self.idx} send={self.send} demand={self.demand} '
                f'reward={self.reward} exp={self.exp} money={self.money} reqpro={self.reqpro}>')


class QuestCatalog:
    def __init__(self, defs, source):
        self.defs = defs
        self.source = source

    @classmethod
    def load(cls, path):
        text = decode_hs_text(path)
        defs = {}
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith('Number_of_'):
                continue
            head, fields = _split_record(line, 2)
            try:
                idx = int(head[0], 10)
                title = int(head[1], 10)
            except (IndexError, ValueError):
                continue
            defs[idx] = QuestDef(idx, title, fields)
        if not defs:
            raise ContentError(f'{path}: no quest records')
        return cls(defs, path)

    def get(self, quest_id):
        try:
            return self.defs.get(int(quest_id))
        except (TypeError, ValueError):
            return None

    def exists(self, quest_id):
        return self.get(quest_id) is not None

    def offered_by(self, snpc):
        return [q for q in self.defs.values() if q.snpc == snpc]

    def kill_quests(self, npccode):
        """Quests whose ReqPro counter this monster feeds (kill-progress, F3)."""
        return [q for q in self.defs.values() if q.reqpro and q.npc == npccode]

    def __len__(self):
        return len(self.defs)

    def __contains__(self, quest_id):
        return self.exists(quest_id)


# ------------------------------------------------------------ NPC templates ---
# hni record layout (FUN_00408a40 tokenizer, positional): idx, Title text id, hsi, NONE,
# then `Key: value` pairs. The record offsets the S2C 0x1A handler copies into the entity
# (spec 0x1A semantics step 3): +0x63C UI, +0x640 Lv, +0x644 type, +0x648 HP.
NPC_ITEM_SLOTS = 120            # item: 0x1E0 chars of %04d ids
NPC_DROP_SLOTS = 120            # Drop: 0x78 x %06d, one per item slot
# FUN_00444100 builds a client-side entity (uid 33000000+) for an event-2 map tile only
# when the template's type (+0x644) is <= 2: town NPCs. Types 3..7 are monsters the server
# spawns with S2C 0x1A.
NPC_CLIENT_SPAWNED_MAX_TYPE = 2

# hni `UI:` = the window an NPC click opens (npc+0xE6C; shop_storage.md 1.1, 1.4, 1.5). The
# same ids in both EN builds (56 merchants, bank idx 97, village transfer idx 117).
UI_NPC_SHOP = 0xD               # 13: FUN_00465a80 lists the record's `item:` column
UI_BANK = 0x1A7                 # 423: Mikomakisho; 2008 opens password dialog 0x201 first
UI_VILLAGE_TRANSFER = 600       # GaranMaria (world-village-transfer)
# EN 2009 only: the guild NPC menu (Moiba, hni 181). Its control 5 sells the template's first
# `item:` id through the ordinary C2S 0x0B (spec_2009 0x474327/0x0B, FUN_00480430 @0x482248),
# whose npc_id is always 0 on the wire (guild_npc_2009 below).
UI_GUILD_NPC_2009 = 0x4BB
# shop_storage.md 3.4 constants: the flea market (stage97_01, MapInfo mode 2 = a field map)
# and the bank tab capacity a new record starts with (premium_cash §3.1; the client allows
# 0..60, items 1887-1889 add 5).
STALL_MAP = 9701
BANK_DEFAULT_SLOTS = 35


class NpcTemplate:
    """One hs/windslayer.hni record: the client's own NPC/monster template (the list at
    game_state+0x4E0 that S2C 0x1A template_index points into)."""
    __slots__ = ('idx', 'position', 'title_text', 'name', 'hsi', 'ai', 'drops', 'shop_items',
                 'quest', 'ui', 'illust', 'lv', 'type', 'hp', 'mp', 'body_atk', 'defense',
                 'weak_atk', 'strong_atk', 'atk_type', 'speed', 'exp', 'attri_atk', 'attri_def')

    def __init__(self, idx, position, title_text, hsi, fields, names):
        f = fields
        self.idx = idx
        self.position = position        # 1-based place in the file = the client list index
        self.title_text = title_text
        self.name = names.get(title_text) or f'npc {idx}'
        self.hsi = hsi
        # `AI:` - 13 ints in 2009, 10 in 2008 (FUN_00409150 -> template+0x254 [+0x250], copied
        # onto the entity by the 0x1A handler: 13 dwords to +0xE50 @0x456C99 [10 to +0xDC0
        # @0x451F67]). The flags the server AI reads are mobai.Flags.of(ai).
        self.ai = _ints(f.get('AI', []))
        ids = _digit_groups(f.get('item', []), NPC_ITEM_SLOTS, 4)
        rates = _digit_groups(f.get('Drop', []), NPC_DROP_SLOTS, 6)
        # (item id, rate) per filled item slot. The rate column is the client's own number;
        # its unit is not verified (per-million reads right: the Pupu card 2030 is 50).
        self.drops = [(i, rates[n]) for n, i in enumerate(ids) if i]
        # The same `item:` column read as a merchant's stock (shop_storage-en-content): the
        # client's shop listing FUN_00465a80 walks record+0x278 (2009 +0x288) up to the FIRST
        # zero id, 0x78 entries at most, so a hole ends the list.
        stock = []
        for i in ids:
            if not i:
                break
            stock.append(i)
        self.shop_items = stock
        self.quest = _int(f.get('Quest'))
        self.ui = _int(f.get('UI'))
        self.illust = _int(f.get('Illust'))
        self.lv = _int(f.get('Lv'))
        self.type = _int(f.get('type'))
        self.hp = _int(f.get('HP'))
        self.mp = _int(f.get('MP'))
        # The 0x1A handler copies these onto the entity (0x456B9E..0x456C10): Body_Atk +0x123C,
        # Weak_Atk +0x11D4, Strong_Atk +0x11D0, Def +0x11E0. The client's own damage estimate
        # (table 0x41A954) hits with Body_Atk for events 1/6, Weak_Atk for 7, Strong_Atk 4/9.
        self.body_atk = _int(f.get('Body_Atk'))
        self.defense = _int(f.get('Def'))
        self.weak_atk = _int(f.get('Weak_Atk'))
        self.strong_atk = _int(f.get('Strong_Atk'))
        self.atk_type = _int(f.get('AtkType'))
        self.speed = _int(f.get('speed'))           # the client stores speed * 0.0001
        self.exp = _int(f.get('Exp'))
        # The element of a type 4..7 template (type - 3: 1 Fire, 2 Ice, 3 Earth, 4 Wind; table
        # 0x41D064): its element attack and the resist of that element (FUN_0041b830
        # [FUN_0041ace0] copies them to +0x11F4 / +0x1200.. [+0x1154 / +0x1160..]; damage.py).
        self.attri_atk = _int(f.get('Attri_Atk'))
        self.attri_def = _int(f.get('Attri_Def'))

    @property
    def is_monster(self):
        """A template the server spawns (FUN_00444100 leaves type > 2 to the server)."""
        return self.type > NPC_CLIENT_SPAWNED_MAX_TYPE

    @property
    def drop_ids(self):
        return [i for i, _ in self.drops]

    @property
    def is_merchant(self):
        """An NPC whose click opens the shop window 0xD (hni `UI: 13`)."""
        return self.ui == UI_NPC_SHOP

    def __repr__(self):
        return f'<NpcTemplate {self.idx} {self.name!r} type={self.type} lv={self.lv} hp={self.hp}>'


class NpcCatalog:
    """hs/windslayer.hni: 180 templates, appended to the client list in file order
    (FUN_00409610 -> CPList::AddTail), so the S2C 0x1A template_index of a record is its
    1-based position in the file. The EN file numbers its records 1..180 in order, so the
    position equals the record idx (= the npccode quests use, hqi NPC/SNPC/ENPC), which
    live test world_movement_npc#21 confirms: templates 2, 3, 4, 6 showed Blue Pupu,
    Well-done Pupu, Blood Pupu and Kamikaze Rat on maps 101 and 102."""

    def __init__(self, defs, source):
        self.defs = defs                                   # idx -> NpcTemplate
        self.source = source
        self._by_position = {d.position: d for d in defs.values()}
        self._first_by_ui = {}                             # ui -> NpcTemplate | None (first_with_ui)

    @classmethod
    def load(cls, path, names):
        text = decode_hs_text(path)
        defs, position = {}, 0
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith('Number_of_'):
                continue
            head, fields = _split_record(line, 4)
            try:
                idx, title = int(head[0], 10), int(head[1], 10)
            except (IndexError, ValueError):
                continue
            position += 1
            defs[idx] = NpcTemplate(idx, position, title, head[2] if len(head) > 2 else '', fields, names)
        if not defs:
            raise ContentError(f'{path}: no NPC records')
        return cls(defs, path)

    def get(self, idx):
        try:
            return self.defs.get(int(idx))
        except (TypeError, ValueError):
            return None

    def template_index(self, idx):
        """The S2C 0x1A template_index for npc idx, or None when the client has no such
        template: an unbound index leaves the entity's +0x11DC NULL (no body, no name,
        nameplate NULL-deref risk at 0x43C4C2), so the caller must not spawn it."""
        d = self.get(idx)
        return None if d is None else d.position

    def at_index(self, template_index):
        return self._by_position.get(template_index)

    def monsters(self):
        return [d for d in self.defs.values() if d.is_monster]

    def merchants(self):
        """The UI-13 templates (56 in both EN builds; idx 7 Smith and 20 "-------" have an
        empty stock)."""
        return [d for d in self.defs.values() if d.is_merchant]

    def shop_list(self, idx):
        """The stock of merchant `idx` (the `npc_id` of C2S 0x0B, window 0xD +0x11C = the
        clicked NPC's hni idx), or None when `idx` is not a merchant. Replaces the KR
        gamedef `npcs.item` / `items.Buy` the old buy handler never even consulted (B4)."""
        d = self.get(idx)
        return list(d.shop_items) if d is not None and d.is_merchant else None

    def first_with_ui(self, ui):
        """The first template (file order) whose `UI:` is `ui`, or None. Cached per catalog, so
        a reload() (a new catalog) starts over."""
        ui = int(ui)
        if ui not in self._first_by_ui:
            self._first_by_ui[ui] = next((d for d in sorted(self.defs.values(), key=lambda t: t.position)
                                          if d.ui == ui), None)
        return self._first_by_ui[ui]

    def __len__(self):
        return len(self.defs)

    def __contains__(self, idx):
        return self.get(idx) is not None


def read_lng(path):
    """{text id: text} from a plaintext hs/*LngKo.lng table (`<id> <text>`, '#' = space)."""
    out = {}
    with open(path, 'rb') as f:
        text = f.read().decode('cp949', 'replace')
    for line in text.splitlines():
        head, _, rest = line.partition(' ')
        if head.isdigit():
            out[int(head)] = rest.replace('#', ' ').strip()
    return out


# ------------------------------------------------------------------- cache ---
_lock = threading.RLock()
_client_dir = DEFAULT_CLIENT_DIR
_client_build = '2008'
_items = _quests = _cards = _names = _portals = _npcs = None
_portals_source = None
_gamedef_conn = None
_gamedef_cache = {}
_map_dests = {}                 # map code -> EN .hmi portal destinations (log aid)
_spawns = {}                    # map code -> [Spawn] (world-template-map)
_gather = {}                    # map code -> {gather node template idx} (item_inventory-gathering)
_lng = {}                       # lng file name -> {text id: text}

# portals.json keys are "<map>_<portal line index>"; 13 rows key a None/empty index.
_PORTAL_KEY = re.compile(r'\d+_\d+')
# A portal tile in an EN .hmi: event="1" and the destination map code in value_num.
_PORTAL_TILE = re.compile(r'<Tile[^>]*event="1"[^>]*value_num="(\d+)"')


def configure(client_dir=None, client_build=None):
    """Point the loader at a client install (config CLIENT_DIR / CLIENT_DIR_2009) of a client
    build ('2008' default, '2009'; config CLIENT_BUILD). The caches are dropped only when the
    directory or the build actually changes: every GameServer construction calls this
    (offline tests build one per test), and re-reading the 2 MB item table each time both
    costs a fifth of a second and lets one thread's reload stall another thread's lookup.

    The build picks the tables that are NOT inside the client files (client-2009-world):
    the generated portal table (portals_en_path), the item-name source (item_name) and the
    item Kind -> equip slot switch (ItemCatalog.client_build, inventory.kind_tables). None
    keeps the current build (a directory-only call, e.g. en_maps.py --client-dir)."""
    global _client_dir, _client_build
    with _lock:
        resolved = _client_dir
        if client_dir:
            resolved = os.path.abspath(os.path.join(HERE, os.path.expanduser(client_dir)))
        build = _client_build if client_build is None else str(client_build)
        if build not in PORTALS_EN_PATHS:
            raise ContentError(f'client build must be one of {sorted(PORTALS_EN_PATHS)}, not {client_build!r}')
        if resolved != _client_dir or build != _client_build:
            _client_dir, _client_build = resolved, build
            reload()
        return _client_dir


def client_dir():
    return _client_dir


def client_build():
    """The client build whose files the caches hold ('2008' until configure says otherwise)."""
    return _client_build


def portals_en_path(build=None):
    """The generated EN portal table of a build (en_maps.py writes it from that build's map
    files: portals_en.json for 2008, portals_en_2009.json for 2009). The 2008 path is read
    from the module attribute each time, so a test that patches PORTALS_EN_PATH still works."""
    build = build or _client_build
    return PORTALS_EN_PATH if build == '2008' else PORTALS_EN_PATHS[build]


def item_max_id():
    """The highest item id the active client's item table holds (2008 4248, 2009 4322): the
    upper bound for anything that names an item id (dev commands, grants)."""
    return items().max_id


def hs_path(name):
    return os.path.join(_client_dir, 'hs', name)


def reload():
    """Drop every cache (GM sub 0x00 `/update`, tests). The next accessor re-reads the files."""
    global _items, _quests, _cards, _names, _portals, _portals_source, _npcs, _gamedef_conn
    global _portal_lines
    with _lock:
        _items = _quests = _cards = _names = _portals = _npcs = _portals_source = None
        _portal_lines = None
        _gamedef_cache.clear()
        _map_dests.clear()
        _spawns.clear()
        _gather.clear()
        _lng.clear()
        import en_maps                  # late: en_maps imports this module
        en_maps.clear_cache()
        if _gamedef_conn is not None:
            try:
                _gamedef_conn.close()
            except sqlite3.Error:
                pass
            _gamedef_conn = None


def items():
    """The EN ItemCatalog (hii, or the client dump when the client files are absent)."""
    global _items
    with _lock:
        if _items is None:
            path = hs_path('windslayer.hii')
            try:
                _items = ItemCatalog.load(path)
                log.info(f'[CONTENT] {len(_items)} EN items from {path}')
            except (OSError, ContentError) as e:
                _items = ItemCatalog.from_dump(ITEM_CATALOG_JSON)
                log.warning(f'[CONTENT] {path}: {e}; falling back to the client dump '
                            f'{ITEM_CATALOG_JSON} ({len(_items)} ids, Type only - no prices, '
                            f'Kind or cooldowns)')
            _items.client_build = _client_build
        return _items


def quests():
    """The EN QuestCatalog (hqi). Empty when the client file is absent: every quest handler
    then refuses instead of acting on KR data."""
    global _quests
    with _lock:
        if _quests is None:
            path = hs_path('windslayer.hqi')
            try:
                _quests = QuestCatalog.load(path)
                log.info(f'[CONTENT] {len(_quests)} EN quests from {path}')
            except (OSError, ContentError) as e:
                _quests = QuestCatalog({}, path)
                log.warning(f'[CONTENT] {path}: {e}; no quest content (every quest is refused)')
        return _quests


def cards():
    global _cards
    with _lock:
        if _cards is None:
            _cards = CardCatalog.from_items(items())
            log.info(f'[CONTENT] {len(_cards)} monster cards (hii Type 2 with CardSpr)')
        return _cards


def lng(name):
    """A client text table (hs/NPCLngKo.lng, hs/MapLngKo.lng: plaintext in the EN client),
    or {} when it is not installed."""
    with _lock:
        if name not in _lng:
            try:
                _lng[name] = read_lng(hs_path(name))
            except OSError as e:
                log.warning(f'[CONTENT] {hs_path(name)}: {e}; no EN texts from it')
                _lng[name] = {}
        return _lng[name]


def npcs():
    """The EN NpcCatalog (hs/windslayer.hni, names from hs/NPCLngKo.lng). Empty when the
    client files are absent: no monster is spawned then, because a template index the
    server cannot vouch for can leave a body-less entity with a NULL nameplate."""
    global _npcs
    with _lock:
        if _npcs is None:
            path = hs_path('windslayer.hni')
            try:
                _npcs = NpcCatalog.load(path, lng('NPCLngKo.lng'))
                log.info(f'[CONTENT] {len(_npcs)} EN NPC templates from {path} '
                         f'({len(_npcs.monsters())} server-spawned monster types)')
            except (OSError, ContentError) as e:
                _npcs = NpcCatalog({}, path)
                log.warning(f'[CONTENT] {path}: {e}; no NPC templates (no monster is spawned)')
        return _npcs


def npc_name(idx):
    """The EN name the client shows for an NPC/monster template (logs only)."""
    d = npcs().get(idx)
    return d.name if d is not None else f'npc {idx}'


def shop_list(npc_id):
    """The EN stock of merchant `npc_id` (hs/windslayer.hni `item:` of a `UI: 13` record), or
    None when that NPC is no merchant (shop_storage-en-content)."""
    return npcs().shop_list(npc_id)


def guild_npc_2009():
    """The EN 2009 guild NPC: the first hni template whose `UI:` opens the guild menu 0x4BB
    (UI_GUILD_NPC_2009) - Moiba, idx 181 (guild.md 1.5) - or None when the loaded hni has none
    (the 2008 build, no client files). Cached with the catalog (reload() drops it).

    Its use: Moiba's billboard sale (send site 0x474327) always arrives with npc_id 0 - the
    quantity dialog 0x10 is closed (FUN_00497e00 zeroes +0x11C, 0x497EA5) before its OK handler
    reads the NPC id (0x474315) - so the server names the NPC itself
    (GameServer._board_sale_npc; p15 live triage 1)."""
    return npcs().first_with_ui(UI_GUILD_NPC_2009)


class Spawn:
    """One server-spawned monster placement from a map file's event-2 tile."""
    __slots__ = ('npc', 'x', 'y', 'value', 'tile')

    def __init__(self, npc, x, y, value, tile):
        self.npc, self.x, self.y, self.value, self.tile = npc, x, y, value, tile

    def __repr__(self):
        return f'<Spawn npc={self.npc} at ({self.x:g},{self.y:g}) tile={self.tile} value={self.value}>'


def map_spawns(map_code, indun=False):
    """[Spawn] for the monsters placed on `map_code` (world-template-map, world doc Q7).
    indun=True reads the 2009 instance-dungeon stage `map_code` (indunAA_BB.hmi, S2C 0xA5
    stage codes, en_maps.load_indun) instead of the stage map of that number.

    Source: the EN map file's event-2 tiles whose NpcId template is a monster (type > 2).
    The client ignores exactly those tiles (FUN_00444100) and builds the type <= 2 ones
    (town NPCs) itself, so a town gets no server spawn. The tile's value_num is kept as
    `value` (15 on every map-102 Pupu tile, 30 on most fields, 300 on bosses - it reads
    like a respawn time in seconds, unverified, so the server keeps MOB_RESPAWN_SECS).
    A tile whose NpcId has no hni template is skipped: its 0x1A would bind no template."""
    import en_maps                      # late: en_maps imports this module
    map_code = int(map_code)
    key = ('indun', map_code) if indun else map_code
    with _lock:
        cached = _spawns.get(key)
        if cached is not None:
            return cached
    data = en_maps.load_indun(map_code) if indun else en_maps.load_map(map_code)
    catalog = npcs()
    out = []
    for tile in (data.npc_tiles() if data is not None else []):
        tpl = catalog.get(tile.npc_id)
        if tpl is None:
            log.warning(f'[CONTENT] map {map_code} tile ({tile.x},{tile.y}) NpcId {tile.npc_id}: '
                        f'no hni template - not spawned')
            continue
        if not tpl.is_monster:
            continue
        x, y = data.spawn_point(tile)
        out.append(Spawn(tile.npc_id, x, y, tile.value, (tile.x, tile.y)))
    with _lock:
        _spawns[key] = out
    return out


# Gather nodes (item_inventory-gathering, item_inventory.md F13 / Q10). hni `type` (+0x644)
# 1 = mineral vein, 2 = herb; `Lv` (+0x640) is the node grade the tool must reach. EN (both
# builds): 118/123/124/125 Common/Imperial/Rare/Mystic Herb (Lv 1/26/56/86), 128/127/126/122
# Common/Imperial/Rare Mineral Vein and Mysterious Miner (Lv 1/26/56/86) - the only type 1/2
# templates the EN hni has.
NODE_TYPE_MINERAL, NODE_TYPE_HERB = 1, 2
GATHER_NODE_TYPES = (NODE_TYPE_MINERAL, NODE_TYPE_HERB)


def gather_nodes(map_code):
    """{hni idx} of the gather nodes placed on `map_code` (the per-map content table of
    item_inventory F13 step 2; Q10 answered from the client's own files).

    A node is a type 1/2 template on one of the map's event-2 tiles. The client builds those
    entities itself (FUN_00444100 keeps every type <= 2 tile, like the town NPCs: no server
    spawn), and each one carries its template's 1-based position in the hni list at entity
    +0xE60 - the `gather_node_record_index` C2S 0x69 sends (spec 0x4685B2/0x69; the gather
    start FUN_00467b00 (2009 FUN_00471960) looks the same index up with RosterLookupByIndex
    and reads +0x644 type / +0x640 grade from it). So the index is NpcCatalog.at_index(),
    and this table only answers "is such a node on this map". Both EN builds place them on
    the herbal farms (x41/x42: 241, 242, 441, ...) and mining areas (x43/x44); 2009 adds
    1501/1502/1601/1602."""
    import en_maps                      # late: en_maps imports this module
    map_code = int(map_code)
    with _lock:
        cached = _gather.get(map_code)
        if cached is not None:
            return cached
    data = en_maps.load_map(map_code)
    catalog = npcs()
    out = set()
    for tile in (data.npc_tiles() if data is not None else []):
        tpl = catalog.get(tile.npc_id)
        if tpl is not None and tpl.type in GATHER_NODE_TYPES:
            out.add(tpl.idx)
    out = frozenset(out)
    with _lock:
        _gather[map_code] = out
    return out


def map_name(map_code):
    """The EN map name (hmi MapInfo name -> hs/MapLngKo.lng), or '' (logs only)."""
    import en_maps                      # late: en_maps imports this module
    data = en_maps.load_map(map_code)
    if data is None or not data.name_text:
        return ''
    return lng('MapLngKo.lng').get(data.name_text, '')


# ------------------------------------------------------------- names / misc ---
def _name_table():
    global _names
    with _lock:
        if _names is None:
            try:
                with open(ITEM_CATALOG_JSON, encoding='utf-8') as f:
                    _names = {int(k): v.get('name', '') for k, v in json.load(f).items()}
            except (OSError, ValueError) as e:
                log.warning(f'[CONTENT] {ITEM_CATALOG_JSON}: {e}; item names unavailable')
                _names = {}
        return _names


def item_name(item_id):
    """The EN name the client shows, from the live catalog dump. Log lines only - the wire
    never carries an item name.

    2009 (client-2009-world): the dump is the 2008 client's (ids 1..4248, and 2009 renamed
    some), so a 2009 install names items from its own plaintext hs/ITMLngKo.lng by the hii
    record's Title text id - the table the client itself draws the names from."""
    try:
        item_id = int(item_id)
    except (TypeError, ValueError):
        return '?'
    if _client_build != '2008':
        d = items().get(item_id)
        name = lng('ITMLngKo.lng').get(d.title_text) if d is not None else None
        return name or f'item {item_id}'
    return _name_table().get(item_id) or f'item {item_id}'


# ------------------------------------------------------------- KR gamedef ---
# arch09-id-shift (ROADMAP_2009_ADDENDUM 3.0 / carry-in C3; systems_2009/pet.md B2 and
# _work/pet/align_kr_en.txt): the EN 2009 hii inserts four EN event items at 4249..4252, so
# the KR gamedef and the EN 2009 table agree up to 4248 and above it EN id = KR idx + 4
# (every one of the 56 new 2009 mall rows equals its KR row once shifted). The client indexes
# items by line order only, so the EN hii of the running build is THE authority for an id;
# every KR row an item id is looked up by goes through kr_item_idx, and every item id read
# out of a KR column goes through en_item_id. The 2008 hii has 4248 rows and no shift.
#
# The audit of every KR-derived number the server uses (C3):
#   - item rows: gamedef_item (below) - stall.py / trade.py NotTrade, packets.cash_duration_type's
#     Cash_T fallback (a server without the client files) - all shifted here;
#   - mall data (prices, Cash_Cls 17-19 pet tabs, gift certificates 3327..3332, the pet food /
#     name ticket / bell ids of cash.py): the EN hii itself (cash.CashDef), never KR;
#   - monster stats and drops, shop lists, quests, cards: the EN hni / hqi / hii (this module);
#     gamedef_npc rows carry KR item ids in `item` - nothing reads that column, and a caller
#     that does must map each id through en_item_id;
#   - portals.json / data.map_codes: map codes only (no item ids);
#   - quest_defs.py: retired (KR quests, hex-decoded, KR item ids); nothing imports it.
# Exe constants are fixed only by the client patch cp-2 (P15).
#
# P15 re-audit (arch09-id-shift owner; the loaders P8 C3 did not cover):
#   - data/ (build_data.py: the KR 4609-row items.json / npcs.json): only data.map_codes is
#     imported (map codes, no item ids);
#   - events.json (login_gift, cash_gift), config STARTING_SKILLS / STARTER_WEAPON /
#     SHOP_EXTRA_ITEMS, bosses / drops (the EN hni Drop column), crafting and cards (the EN
#     hii / hni): EN ids by construction - nothing in them is KR-derived;
#   - guild.py BOARD_ITEMS (the 0xBA / 0xBB / sub 185 board item) and the pet food / bell /
#     ticket the client sends: EXE constants, not data - they follow config CLIENT_ITEM_IDS
#     (exe_item_id / en_item_from_exe below), never the KR table;
#   - the test sweep test_pets.IdShiftAudit checks every server constant above 4248 against
#     the EN 2009 hii row it must be (Type / Kind / Cash).


# The 17 hard-coded item-id sites of the 2009 exe (CLIENT_PATCH_SET_RE 8.2), by meaning, as the
# EN ids the cp-2 patched exe uses; the stock exe compares against the KR ids (EN - 4).
# config CLIENT_ITEM_IDS says which set the installed exe has: 'en' (cp-2) or 'kr' (stock).
CLIENT_ITEM_IDS = ('en', 'kr')
EXE_ID_SITES = {
    'premium_board': (4283,),        # 0x46DB2B switch base, 0x45DBD2 / 0x45DD4A sprite 0x146
    'board': (4284,),                # 0x44FCB8, 0x45DBC3 / 0x45DD3B sprite 0x145, 0x47E846 sub 185
    'pet_bell': (4285,),             # 0x44FD72 (FUN_0044f070 Type-0 use gate)
    'pet_food': (4286, 4287, 4288, 4289),   # FUN_0046d640 auto-feed / manual range
    'pet_name_ticket': (4322,),      # 0x46DB2B switch slot 0x27 -> window 0x4CB
}
EXE_ID_ITEMS = frozenset(i for ids in EXE_ID_SITES.values() for i in ids)


def exe_item_id(en_id, client_item_ids='en'):
    """The id the installed 2009 exe uses for the EN item `en_id` at its hard-coded sites:
    `en_id` itself on a cp-2 exe ('en'), KR = EN - 4 on the stock exe ('kr'). Only for the
    EXE_ID_ITEMS (a board item the server sends, a constant the client compares); every other
    id is the EN hii's in both, so it is returned as it is."""
    en_id = int(en_id)
    if str(client_item_ids) == 'kr' and en_id in EXE_ID_ITEMS:
        return en_id - KR_SHIFT
    return en_id


def en_item_from_exe(exe_id, client_item_ids='en'):
    """The EN item an id from one of the exe's hard-coded sites means (exe_item_id's inverse):
    on the stock exe ('kr') a pet food the auto-feed sends as KR 4282 is EN 4286. None for an
    id that is no exe-site id of that set (on 'kr', EN 4286 itself is not what the exe sends)."""
    exe_id = int(exe_id)
    for en_id in EXE_ID_ITEMS:
        if exe_item_id(en_id, client_item_ids) == exe_id:
            return en_id
    return None
KR_SHIFT_ABOVE = EN_ITEM_MAX_ID              # 4248: the last id KR and EN 2009 share
KR_SHIFT = 4
EN_ONLY_IDS_2009 = range(KR_SHIFT_ABOVE + 1, KR_SHIFT_ABOVE + KR_SHIFT + 1)   # 4249..4252


def _id_build(client_build):
    return _client_build if client_build is None else str(client_build)


def kr_item_idx(item_id, client_build=None):
    """The KR gamedef idx of an EN item id of `client_build` (None = the loaded build), or None
    for the four EN-only 2009 event items 4249..4252 (no KR row)."""
    item_id = int(item_id)
    if _id_build(client_build) != '2009' or item_id <= KR_SHIFT_ABOVE:
        return item_id
    return None if item_id in EN_ONLY_IDS_2009 else item_id - KR_SHIFT


def en_item_id(kr_idx, client_build=None):
    """The EN item id of `client_build` (None = the loaded build) for a KR gamedef item idx:
    +4 above 4248 in 2009 (KR 4282 Pet Food 250 = EN 4286)."""
    kr_idx = int(kr_idx)
    if _id_build(client_build) != '2009' or kr_idx <= KR_SHIFT_ABOVE:
        return kr_idx
    return kr_idx + KR_SHIFT


def _gamedef():
    """The KR content DB, opened READ-ONLY: a server without gamedef.sqlite3 gets an error
    (every row None) instead of sqlite creating an empty file next to it."""
    global _gamedef_conn
    with _lock:
        if _gamedef_conn is None:
            uri = pathlib.Path(os.path.abspath(GAMEDEF_PATH)).as_uri() + '?mode=ro'
            _gamedef_conn = sqlite3.connect(uri, uri=True, check_same_thread=False)
            _gamedef_conn.row_factory = sqlite3.Row
        return _gamedef_conn


def gamedef_row(table, idx, columns='*'):
    """One row of the KR content DB, cached. Only for numbers the EN client files do not
    carry (monster HP/Def/Exp/Lv/drops, NotTrade/PvPItem); never for an id or a price
    (F7: the EN files are the authority). `idx` is the KR idx: an item row goes through
    gamedef_item (the 2009 id shift)."""
    key = (table, columns, int(idx))
    if key in _gamedef_cache:
        return _gamedef_cache[key]
    row = None
    try:
        with _lock:                  # one connection shared by every thread: one query at a time
            cur = _gamedef().execute(f'SELECT {columns} FROM {table} WHERE idx=?', (int(idx),))
            found = cur.fetchone()
        row = dict(found) if found else None
    except (sqlite3.Error, OSError) as e:
        log.warning(f'[CONTENT] gamedef {table}[{idx}]: {e}')
    _gamedef_cache[key] = row
    return row


def gamedef_npc(npccode):
    """KR `npcs` row for a monster npccode (HP, Def, Exp, Lv, item drop list). Its item ids
    are KR idx: map them with en_item_id before using one."""
    return gamedef_row('npcs', npccode)


def gamedef_item(item_id, client_build=None, columns='*'):
    """The KR `items` row of an EN item id of `client_build` (None = the loaded build): KR idx
    = kr_item_idx (a 2009 id above 4248 is KR + 4; 4249..4252 have none -> None). Use it ONLY
    for columns the hii lacks (NotTrade, PvPItem; Cash_T without the client files): its Kind
    differs from EN for 289 items (item_inventory 3.1)."""
    try:
        kr_id = kr_item_idx(item_id, client_build)
    except (TypeError, ValueError):
        return None
    return None if kr_id is None or kr_id < 1 else gamedef_row('items', kr_id, columns)


# ------------------------------------------------------------------ portals ---
def _load_kr_portals():
    """The KR-derived `portals.json`, malformed rows dropped (world-portal-guards): 13 key a
    `None` or empty index (`None_None`, `_`, `1002_None`) and the rest carry a null
    destination. Only the last-resort fallback now: 237 of the 594 EN portals are missing
    from it and 132 of its arrivals disagree with the EN layout (world doc B14)."""
    try:
        with open(PORTALS_PATH, encoding='utf-8') as f:
            raw = json.load(f)
    except (OSError, ValueError) as e:
        log.warning(f'[CONTENT] {PORTALS_PATH}: {e}; no portals (every 0x7E is ignored)')
        raw = {}
    table, dropped = {}, []
    for key, row in raw.items():
        if _PORTAL_KEY.fullmatch(str(key)) and isinstance(row, list) and len(row) >= 3                 and all(v is not None for v in row[:3]):
            table[key] = row
        else:
            dropped.append(key)
    if dropped:
        log.info(f'[CONTENT] {len(table)} portals from {PORTALS_PATH}; '
                 f'{len(dropped)} malformed key(s) dropped: {sorted(dropped)}')
    return table


def _rows_to_table(rows):
    return {key: [int(r['dest']), float(r['x']), float(r['y'])] for key, r in rows.items()
            if _PORTAL_KEY.fullmatch(str(key)) and r.get('dest')}


def portals():
    """The portal table as `{"<map>_<collision line index>": [next_map, x, y]}`.

    world-portal-table-en: the EN client's own map files are the source. In order:
      1. `server/portals_en.json`, generated by `python en_maps.py` from every EN
         `hs/stageAA_BB.hmi` + `.hsi` line list (593 portals, the 101_23 -> 102 live
         anchor asserted at generation);
      2. the same table built in memory from the installed client files, when the JSON is
         missing (a copied server that has the client but not the generated file);
      3. the KR `portals.json`, only when neither exists, so a bare server still starts.
    `portals_source()` says which one is live; the portal log names it on a miss."""
    global _portals, _portals_source
    with _lock:
        if _portals is not None:
            return _portals
        table, source = None, None
        path = portals_en_path()            # per client build (client-2009-world)
        try:
            with open(path, encoding='utf-8') as f:
                table = _rows_to_table(json.load(f).get('portals', {}))
            source = path
        except (OSError, ValueError, AttributeError, TypeError, KeyError) as e:
            log.warning(f'[CONTENT] {path}: {e}; building the EN portal table '
                        f'from the client map files')
            import en_maps              # late: en_maps imports this module
            rows, report = en_maps.build_portal_table()
            if rows:
                table, source = _rows_to_table(rows), f'{client_dir()}/hs/*.hmi (in memory)'
                bad = en_maps.check_live_portals(rows)
                if bad:
                    log.error(f'[CONTENT] EN portal table contradicts the live captures: {bad}')
        if not table:
            table, source = _load_kr_portals(), f'{PORTALS_PATH} (KR fallback)'
            log.warning(f'[CONTENT] no EN portal table: using the KR {PORTALS_PATH} '
                        f'({len(table)} rows; 237 EN portals missing from it)')
        else:
            log.info(f'[CONTENT] {len(table)} EN portals from {source}')
        _portals, _portals_source = table, source
        return _portals


def portals_source():
    portals()
    return _portals_source


_portal_lines = None


def portal_line(map_code, portal_code):
    """The collision line [x_start, y, x_end] of a portal (the generated table's `line`), or
    None. The flea-market return uses it (world-flea-return): the market's single exit tile
    (stage97_01 Layer 53, value_num 101) names map 101 whatever town the player came from,
    so the server stands him back on the town's own market portal instead."""
    global _portal_lines
    with _lock:
        if _portal_lines is None:
            lines = {}
            try:
                with open(portals_en_path(), encoding='utf-8') as f:
                    for key, row in (json.load(f).get('portals') or {}).items():
                        line = row.get('line') if isinstance(row, dict) else None
                        if line and len(line) == 3:
                            lines[key] = [float(v) for v in line]
            except (OSError, ValueError, AttributeError, TypeError):
                pass
            _portal_lines = lines
        return _portal_lines.get(f'{int(map_code)}_{int(portal_code)}')


def portal(map_code, portal_code):
    """(next_map, x, y) for a portal on `map_code`, or None when it is not mapped. The
    caller must do nothing on None: re-loading the same map duplicates the player entity
    (world-portal-guards)."""
    row = portals().get(f'{int(map_code)}_{int(portal_code)}')
    if not row or len(row) < 3:
        return None
    return int(row[0]), float(row[1]), float(row[2])


def map_file(map_code):
    """The client's own map file for a map code: sprintf './hs/stage%02u_%02u.hmi'
    (map_code/100, map_code%100) at 0x0044EB68, which is what S2C 0x03/0x08 make it load."""
    map_code = int(map_code)
    return hs_path(f'stage{map_code // 100:02d}_{map_code % 100:02d}.hmi')


def map_destinations(map_code):
    """The destination map codes of every portal tile on `map_code`, read from the EN map
    file itself: `<Tile ... event="1" value_num="<dest>"/>` (world_movement_npc.md 1.5).

    Only the destinations, not the indexes (the line indexes are en_maps.py's portal table).
    This answers "which maps does this map actually lead to", which is what an unknown
    portal key is logged with (world-portal-guards). Empty when the client files are not
    installed - it is a log aid, never a gate."""
    map_code = int(map_code)
    with _lock:
        cached = _map_dests.get(map_code)
        if cached is not None:
            return cached
    try:
        text = decode_hs_text(map_file(map_code))
    except (OSError, ContentError) as e:
        log.debug(f'[CONTENT] map {map_code}: {e}; no EN portal destinations')
        text = ''
    dests = []
    for tile in _PORTAL_TILE.finditer(text):
        dest = int(tile.group(1))
        if dest and dest not in dests:
            dests.append(dest)
    with _lock:
        _map_dests[map_code] = dests
    return dests
